name: tr_business_card_clone1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_entity_extraction: ^0.11.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^13.1.0
  sqflite: ^2.3.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  flutter_easyloading: ^3.0.5
  google_mlkit_text_recognition: ^0.11.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
